CC=gcc
CFLAGS=-W -Wall -g
OBJS=1-1.o 1-2.o 1-3.o 1-4.o 1-5.o 1-6.o 1-7.o 1-8.o 1-9.o
EXECS=1-1 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9

all: $(EXECS)

1-1: 1-1.o
	$(CC) $(CFLAGS) 1-1.o -o 1-1

1-2: 1-2.o
	$(CC) $(CFLAGS) 1-2.o -o 1-2

1-3: 1-3.o
	$(CC) $(CFLAGS) 1-3.o -o 1-3

1-4: 1-4.o
	$(CC) $(CFLAGS) 1-4.o -o 1-4

1-5: 1-5.o
	$(CC) $(CFLAGS) 1-5.o -o 1-5

1-6: 1-6.o
	$(CC) $(CFLAGS) 1-6.o -o 1-6

1-7: 1-7.o
	$(CC) $(CFLAGS) 1-7.o -o 1-7

1-8: 1-8.o
	$(CC) $(CFLAGS) 1-8.o -o 1-8

1-9: 1-9.o
	$(CC) $(CFLAGS) 1-9.o -o 1-9

clean:
	rm -f $(OBJS) $(EXECS)

1-1.o: 1-1.c
1-2.o: 1-2.c
1-3.o: 1-3.c
1-4.o: 1-4.c
1-5.o: 1-5.c
1-6.o: 1-6.c
1-7.o: 1-7.c
1-8.o: 1-8.c
1-9.o: 1-9.c

